name: Publish documentation to project website and package to the Maven Central Repository
on:
  [push]
#  release:
#    types: [created]
jobs:
  publish-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate API Doc
        run: sbt doc
      - name: Make API Doc directory outside repository
        run: mkdir -p ../api_docs
      - name: Move API Docs to outside directory
        run: |
          source .workflow-scripts/put_scala_docs_aside.sh ./target ../api_docs
          cp .workflow-scripts/move_scala_docs.sh ../api_docs/
          cp .workflow-scripts/update_json_api_versions.py ../api_docs/
          cd ..
          bash $(pwd)/api_docs/move_scala_docs.sh ./api_docs ./target2 ./api_docs 'some_path_to_some_json'
#        run: mv target/scala-[0-9].[0-9][0-9] ../api_docs/
#      - name: git checkout master
#        run:  |
#          git fetch
#          git checkout gh-pages
#      - name: check something
#        run: ls ../api_docs
#      - name: something else2
#        run: pwd
#      - name: something else3
#        run: ls ../

#  publish-package:
#    runs-on: ubuntu-latest
#    needs: [publish-doc]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Publish package
#        run: mvn --batch-mode deploy
#        env:
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}