name: Publish documentation to project website and package to the Maven Central Repository
on:
  [push]
#  release:
#    types: [created]
jobs:
  publish-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
#      - name: Generate API Doc
#        run: sbt +doc
      - name: something else1
        run: pwd
      - name: move doc versions to outside
        run: mv target ../
      - name: git checkout master
        run:  |
          git fetch
          git checkout master
      - name: something else2
        run: pwd
      - name: something else3
        run: ls ../
      - name: something else3
        run: ls ../json-logic-scala/

#  publish-package:
#    runs-on: ubuntu-latest
#    needs: [publish-doc]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Publish package
#        run: mvn --batch-mode deploy
#        env:
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}