name: Test Coverage CI
on: [push]
jobs:
  retrieve-scala-versions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Retrieve Scala Versions from build.sbt file
        id: set-matrix
        run: |
          outputScalaVersion=$(sbt +scalaBinaryVersion | awk '/\[info\] [0-9]\.[0-9]+/{print}')
          echo $outputScalaVersion
          echo "AAAA"
          echo $outputScalaVersion | grep "[info]"
          echo $outputScalaVersion | grep -oE ".info. 2.12"
          something_to_show=$(echo $outputScalaVersion | grep -P -o "\[info\]\s[0-9]\.[0-9]+")
          echo "$something_to_show"
          echo "BBBB"
          scala_versions=$(echo "$outputScalaVersion" | grep -E -o "\[info\] [0-9]\.[0-9][0-9]")
          echo "$scala_versions"
          echo "CCCC"
          scala_versionsee=$(echo "$scala_versions" | grep "[0-9]\.[0-9][0-9]")
          echo "$scala_versionsee"
          run: echo ::set-output name=matrix::"${scala_versions[@]}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Sbt Test and Generate Report on Multiple Scala Versions
        run: |
          sbt +coverage +test
          sbt +coverageReport
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./target/scala-[0-9].[0-9][0-9]

  upload-coverage:
    runs-on: ubuntu-latest
    needs: [retrieve-scala-versions, test-coverage]
    strategy:
      fail-fast: false
      matrix:
        scala_version: ${{ fromJson(needs.retrieve-scala-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: ./target/
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/scala-${{ matrix.scala_version }}/
          flags: unittests,${{ matrix.scala_version }}
          name: codecov-json-logic-scala
          fail_ci_if_error: true
          verbose: true